spring.application.name=hr-source
okta.org-url=${OKTA_ORG_URL}
okta.api-token=${OKTA_API_TOKEN}
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./data/hrdb
spring.jpa.hibernate.ddl-auto=update